### PR TITLE
Size & Position Config Options

### PR DESCRIPTION
**Pull request by oversword**
- Padding, spacing & offset configs added for each button group
- New SizeScheme file added to hold new config logic
- Skew changed to be a gradient instead of a distance
- Allowed swapping the order of the pages (no consistency checks implemented)
- Arbitrary numbers reduced, and better math implemented

### CODE REVIEW

**Comment by oversword** [comment]
By the way, I have not checked that an un-customised version of this is identical to the original
If I've missed anything there should be a config option for it

**Comment by RadRussianRus** [comment]
I see that you've done a lot but I can't merge it right now.
The thing is that it's too complex for one pull request. Please split it to multiple PRs so it would be easier to review and test.

**Comment by RadRussianRus** [comment]
From what I see here there should be about 4 pulls:
1. Better math and arbitrary number reducing
2. Skew changed to be a gradient instead of a distance
3. SizeScheme with padding, spacing & offset configs added for each button group
4. Swapping the order of the pages

**Comment by oversword** [comment]
You thinks that's complex? How do you feel about skews on loop item backgrounds, animated "peek" effect on hover, textured buttons, & border animations?

**Comment by RadRussianRus** [comment]
It seems you don't get my point.

You're proposing **multiple** changes and sending them as **one** pull request. Also you're proposing changes like `normalizeState` function though it's quite hard to understand why do code needs it in first place.

This combination is complex for one pull request. Please split it to multiple PRs so it would be easier to review and test.

**Pull request closed without merging**
